/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: 4613732

*/

const sum = (max) => {
  const ns = [1,2];
  let next = ns[ns.length - 1] + ns[ns.length - 2];

  while (next < max) {
    ns.push(next);
    next = ns[ns.length - 1] + ns[ns.length - 2];
  }

  return ns.filter(item => item % 2 === 0).reduce((accumulator, currentValue) => accumulator + currentValue, 0);
}

module.exports = sum;